version: "3.9"
   
services:
  mydocs:
    image: claudiocandio/mydocs:latest
    container_name: mydocs
    restart: unless-stopped
    entrypoint: /mydocs_sqlite/mydocs_run.sh
    #volumes:
    #  - ./settings.py:/mydocs_sqlite/mydocs/settings.py
    #  - ./db.sqlite3:/mydocs_sqlite/db.sqlite3
    ports:
      - "8000:8000"

